---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
# Schedule {#schedule}

All lectures are in SN 3060 unless otherwise stated

This is a tentative revision of the schedule following the MUNFA strike.

This revised version fo the schedule will be confirmed after discussion with the class.

- Thurs Jan 5: Introduction
- Fri Jan 6: Population biology with discrete and continuous variables
- Tues Jan 10: ---
- Thurs Jan 12: **CSF 2218** Introduction to Rmarkdown and tidyverse **Assignment 1 is assigned**
- Fri Jan 13: Geometric growth
- Tues Jan 17: Exponential growth
- Thurs Jan 19: **CSF 2218** Numerical solutions and graphing population data **Assignment 2 is assigned**
- Fri Jan 20: Exponential growth
- Tues Jan 24: Density dependence and logistic growth
- Thurs Jan 26: Density dependence and logistic growth **Assignments 1 & 2 are due**
- Fri Jan 27: Discrete time models with density dependence

MUNFA STRIKE

- Thurs Feb 16: Age-structured models
- Fri Feb 17: **CSF 2218** Numerical analysis of stage-structured models **Assignment 3 is assigned**

WINTER BREAK
(**Exam I will be posted on Tuesday Feb 21. Exam I is now a takehome exam due on Monday April 10.**)

- Tues Feb 28: Stage-structured models
- Thurs Mar 2: Stage-structured models
- Fri Mar 3: Density dependence in stage-structured models **Assignment 3 is due**
- Tues Mar 7: Metapopulation models
- Thurs Mar 9: Continuous space models 
- Fri Mar 10: Disease dynamics
- Tues Mar 14: The net reproduction number
- Thurs Mar 16: **EXAM II** (Only material since returning from the strike)
- Fri Mar 17: What is evolutionary ecology?
- Tues Mar 21: Haploid selection model 
- Thur Mar 23: [Selection coefficients for COVID-19 variants](https://www.zoology.ubc.ca/~otto/Talks/SSE2022_Otto.pdf)
- Fri Mar 24: **CSF 2218** Estimating selection coefficients **Assignment 4 is assigned**
- Tues Mar 28: The evolutionary ecology of pathogens
- Thurs Mar 30: The evolutionary ecology of COVID-19
- Fri Mar 31:  The evolutionary ecology of hosts **Assignment 4 is due**
- Tues Apr 3: The evolution of reproductive effort in plants
- Thurs Apr 5: Evolutionarily stable and convergent stable strategies
- Fri Apr 6: Review

TBD **FINAL EXAM** (all course material) 




